syn on
"set nu
set si
set hls
set smartindent
set hid
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set bufhidden=hide
set nowrap
set laststatus=2
set ruler
set backspace=indent,eol,start
set formatoptions=croq
set sm
set printoptions=number:y,paper:letter
set pfn=:h9
set incsearch
set foldmethod=syntax
" vertical splitting will open the new window on the right. 
set splitright
"http://vim.wikia.com/wiki/Highlight_current_line
set cursorline
set ruler
set bg=light
set ic
set fileencodings=ucs-bom,utf-8,latin2


" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

Plug 'vim-airline/vim-airline'

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

Plug 'tpope/vim-fugitive'
Plug 'vivien/vim-linux-coding-style'
Plug 'jlanzarotta/bufexplorer'
Plug 'vim-scripts/DoxygenToolkit.vim'
Plug 'vim-scripts/ScrollColors'
Plug 'vim-scripts/Colour-Sampler-Pack'
Plug 'vim-scripts/sokoban.vim'
Plug 'vim-scripts/mimicpak'


"" Any valid git URL is allowed
"Plug 'https://github.com/junegunn/vim-github-dashboard.git'
"
"" Multiple Plug commands can be written in a single line using | separators
"Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
"
"" On-demand loading
"Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
"Plug 'tpope/vim-fireplace', { 'for': 'clojure' }
"
"" Using a non-master branch
"Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }
"
"" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
"Plug 'fatih/vim-go', { 'tag': '*' }
"
"" Plugin options
"Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }
"
"" Plugin outside ~/.vim/plugged with post-update hook
"Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
"
"" Unmanaged plugin (manually installed and updated)
"Plug '~/my-prototype-plugin'

" Initialize plugin system
call plug#end()
